global_costmap:
  global_frame: map  #地图坐标系
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 5.0
  static_map: true
  rolling_window: false
  inflation_radius: 0.5
  transform_tolerance: 1.0
  # plugins:
    # - {name: static_layer,            type: "costmap_2d::StaticLayer"}
  #   - {name: obstacle_2Dlayer,          type: "costmap_2d::VoxelLayer"}
  #   - {name: obstacle_3Dlayer,          type: "costmap_2d::VoxelLayer"}
    # - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}