local_costmap:
  global_frame: map
  robot_base_frame: base_footprint  # odom  base_link  base_footprint
  update_frequency:  15.0
  publish_frequency: 10.0
  static_map: false #不需要静态地图，可以提升导航效果
  rolling_window: true #是否使用动态窗口，默认为false，在静态的全局地图中，地图不会变化
  width: 5 # 局部地图宽度 单位是 m
  height: 5 # 局部地图高度 单位是 m
  resolution: 0.1
  inflation_radius: 0.4
  transform_tolerance: 1.0 # 局部地图分辨率 单位是 m，一般与静态地图分辨率保持一致
  
  # plugins:
 
  #  - {name: obstacle_2Dlayer,          type: "costmap_2d::VoxelLayer"}
  #  - {name: obstacle_3Dlayer,          type: "costmap_2d::VoxelLayer"}
  # #  - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
  #  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}